#  抛出异常 ( throw)

​        声明抛出异常是Java中处理异常的第二种方式

* 如果一个方法中的语句(执行时)可能会发生异常，但是不能确定如何处理这种异常，则此方法应当 **显示地声明抛出异常** ，表明该方法将 **不对** 异常进行处理，而是抛给方法的 **调用者** 来处理。

* 在 **方法声明** 中使用 **throws** 子句可以声明抛出异常的列表， throws 后面的异常类型可以是方法中的异常类型，也可以是它的父类。

  ```java
  public class TestThrow {
  	public static void main(String[] args) {
  		Demo demo = new Demo();
  		try {
  			demo.test();
  		}
  		// 在 try 语法块中调用函数，后面的 catch 可以 catch 到调用的函数抛出的异常
  		catch(Exception e) {
  			System.out.println(e.getMessage());
  		}
  	}
  }
  class Demo {
  	int i;
  	// 这里使用了 throws ，将产生的异常抛调用者
  	public void test() throws Exception{
  		i = 0;
  		System.out.println(3/i);
  	}
  }
  ```
  
* 子类继承父类时，要 **重写** 父类的 **throws** ，且不能抛出比父类 **范围更大** 的异常。

* Java 异常类对象除了自动生成抛出外，也可以根据需要人工创建并抛出。抛出的异常必须是 **Throwable** 或其子类的实例。

  ```java
  function myException() throws Exception {
      IOException exp = new IOException("自定义的message");
  	throw e;
  }
  ```
  ## 创建自定义的异常类
  
  ​        可以自定义异常类 MyException，用于描述错误信息。自定义的 **异常类** 必须 **继承现有的异常类**。
  
  ​        特殊情况下可以定义自己的异常类（这种情况比较少见）。
  
  ```java
  class MyException extends Exception {
  	private int idNumber;
  	
  	//新的构造方法拓展了 id 参数
  	public MyException(String message,int id) {
  		super(message);
  		this.idNumber = id;
  	}
  	
  	public int getId() {
  		return this.idNumber;
  	}
  }
  ```
  
  

